# -*- coding: utf-8 -*-
"""Pandas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wh8DxhocRi2sR6UaM0kB9cVjoe3q_o08
"""

import pandas as pd

"""Create Dataframes"""

data={
    "Name":['John',"peter","Lisa"],
    "Age":[25,28,31],
    "Gender":["Male","Male","Female"]

}

df=pd.DataFrame(data)
print(df)


list = [ 'Hii', 'my', 'name', 'is', 'sohail', 'ali']
df=pd.DataFrame(list)
print(df)



# cchnage data type
Data = [ ['Robert', 30], ['Sam', 25], ['Diana', 20], ['Mark', 33] ]
Labels=['Name','Age']

df=pd.DataFrame(Data,columns=Labels)
df['Age'] = df['Age'].astype(float)
print(df)

train=pd.read_csv('/content/Random.csv')
df=train.copy()

print(df.info())
print(df.head(1))
print(df.describe())

text_file=pd.read_csv('/content/What is Diabetes.txt' ,sep="\s")
print(text_file)

# d2={
#     'student':['Arnob','Ayush','Mrinual','john'],
#     'Rank':[1,3,4,5],
#     'Marks':['A','B','C','D']
# }
# df=pd.DataFrame(d2)
# print(df)
# print(df.index)


dict = {"Sales": {'Name': 'Shyam',
                  'Age': 23, 'Gender': 'Male'},
        "Marketing": {'Name': 'Neha',
                      'Age': 22, 'Gender': 'Female'}}
df=pd.DataFrame(dict)
print(df)

print(df.columns)
print("Row and Column :" ,df.axes)

print("shape:", df.shape)
print('Dimension:', df.ndim)
print("values:", df.values)

d3 = {
    'Male': pd.Series([32, 45, 33], index=['A', 'B', 'C']),
    'Female': pd.Series([23, 25, 32], index=['A', 'B', 'C'])
}

df = pd.DataFrame(d3)
print("DataFrame:\n", df)

d4= {'Male' : pd.Series([32, 52, 44], index=['PHYSICS', 'MATH', 'CHEMISTRY']),
   'Female' : pd.Series([23, 25, 32], index=['PHYSICS', 'MATH', 'CHEMISTRY'])}

df=pd.DataFrame(d4)
print(df)

print(df.loc['PHYSICS'])
print(df.iloc[2])
print(df.isnull())

df.head()
result_mapping = {"PHYSICS": 'F', "MATH": 'A', "CHEMISTRY": 'B'}
df['Result']=df.index.map(result_mapping)
df.head()

# data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
#         'Height': [5.1, 6.2, 5.1, 5.2],
#         'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}

# df= pd.DataFrame(data)



# # df.insert(2, "Age", [21, 23, 24, 21], True)
# df2=df.assign(Age= [21, 23, 24, 21])
# df2.head()

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

index1=[0,1,2,3]


data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

index=[4,5,6,7]
df3=pd.DataFrame(data1,index=index1)


df4=pd.DataFrame(data2,index=index)
# print(pd.concat( [df3,df4],axis=1,join='inner'))
result = df3.join(df4, lsuffix='_df3', rsuffix='_df4', how='outer')
print(result)

"""## **Selecting, Extracting and Slicing Dataframes Pandas**"""

data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}

df= pd.DataFrame(data)
df.head()


col_name=df.Name
print(col_name)

row_print=df.iloc[0]
print(row_print)


filterd=df[df.Height>6]
print(filterd)


extracted_intVal=df.iloc[0,2]
print(extracted_intVal)

extracted_labVal=df.at[2,"Height"]
print(extracted_labVal)


sliced_df=df.iloc[0:1,0:2]
print(sliced_df)

"""# Pandas Series"""

data2=[10,20,30,40,50]
index_labels=["Row1","Row2","Row3","Row4","Row5"]
s=pd.Series(data2,index=index_labels)
print(s)
print(s[2])
print(s.ndim)
print(s.size)
print(s.values)
print(s.index)
print(s.dtype)

data3=[50,60,70,80,90]
s2=pd.Series(data3)
def demo(s,s2):
  return s+s2
print(demo(s,s2))

"""# Clean Data"""

df=pd.read_excel("/content/Customer Call List.xlsx");

"""# Remove Duploicates"""

df=df.drop_duplicates()
df



"""# Delete Columns"""

df = df.drop(columns='Not_Useful_Column')
df

"""# Strip"""

df['Last_Name'] = df['Last_Name'].str.replace(r"[./_]", "", regex=True)
df
df['Address']=df['Address'].str.split(',',1,expand=True)
df

